#!/bin/bash


set -euo pipefail  # 遇到错误立即退出

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# ========== 配置参数 ==========
MODEL_NAME="internvl2"
MODEL_PATH="OpenGVLab/InternVL2-8B"
W_BIT=2
W_GROUP=128
A_BIT=16
DATASET="wikitext2"
N_SAMPLES=32
SCALE_FILE_NAME="internvl2_8b_w${W_BIT}g${W_GROUP}.pt"
SCALE_PATH="$REPO_ROOT/scale_cache/mbq/$SCALE_FILE_NAME"
RESULT_DIR="$REPO_ROOT/outputs/ppl"

# ========== 创建目录 ==========
mkdir -p "$RESULT_DIR"

if [ ! -f "$SCALE_PATH" ]; then
    echo "ERROR: MBQ scale file not found: $SCALE_PATH"
    echo "Set SCALE_PATH to an existing torch.save file generated by main_quant.py."
    exit 1
fi

echo "=========================================="
echo "MBQ PPL Evaluation"
echo "=========================================="
echo "Model: $MODEL_NAME"
echo "Bits: W${W_BIT}A${A_BIT}"
echo "Dataset: $DATASET"
echo "Scale: $SCALE_PATH"
echo "=========================================="

echo "Evaluating quantized model..."


python eval_ppl.py \
    --model $MODEL_NAME \
    --model_args pretrained=$MODEL_PATH \
    --dataset $DATASET \
    --n_samples $N_SAMPLES \
    --scale_path $SCALE_PATH \
    --w_bit $W_BIT \
    --w_group $W_GROUP \
    --a_bit $A_BIT \
    --pseudo_quant \
    --output_path $RESULT_DIR/mbq_w${W_BIT}_ppl.json \
    --verbose

