#!/bin/bash
# MBQ Quick PPL Evaluation Script
# 快速 PPL 评估脚本，用于检验量化效果

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# ========== 配置参数 ==========
GPU_ID="${GPU_ID:-5}"  # GPU device ID. Override with: GPU_ID=3 bash ...
MODEL_NAME="${MODEL_NAME:-internvl2}"
MODEL_PATH="${MODEL_PATH:-OpenGVLab/InternVL2-8B}"
W_BIT="${W_BIT:-2}"
W_GROUP="${W_GROUP:-32}"
A_BIT="${A_BIT:-16}"
DOUBLE_QUANT_SCALE_BIT="${DOUBLE_QUANT_SCALE_BIT:-4}"
DOUBLE_QUANT_SCALE_GROUP="${DOUBLE_QUANT_SCALE_GROUP:-32}"
DATASET="${DATASET:-wikitext2}"
DATA_PATH="${DATA_PATH:-}"
N_SAMPLES="${N_SAMPLES:-256}"
PYTHON_BIN="${PYTHON_BIN:-/home/users/Mayinyi/anaconda3/envs/mbq/bin/python}"
SCALE_FILE_NAME="${SCALE_FILE_NAME:-internvl2_8b_w2g32_scale_reweight_true_svd_1.0_mixed_0.0.pt}"
RUN_IN_BACKGROUND="${RUN_IN_BACKGROUND:-0}"
SCALE_PATH="$REPO_ROOT/scale_cache/mbq/$SCALE_FILE_NAME"
RESULT_DIR="$REPO_ROOT/outputs/ppl"
RUN_TS="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="$RESULT_DIR/eval_quant_w${W_BIT}_${RUN_TS}.log"
RESULT_JSON="$RESULT_DIR/mbq_w${W_BIT}_${RUN_TS}_ppl.json"

# ========== 创建目录 ==========
mkdir -p "$RESULT_DIR"
: > "$LOG_FILE"
exec >> "$LOG_FILE" 2>&1

export PYTHONPATH="${PYTHONPATH:-.}"
export HF_ENDPOINT="${HF_ENDPOINT:-https://hf-mirror.com}"
export HF_TOKEN="${HF_TOKEN:-YOUR_HF_TOKEN_HERE}"

echo "========================================="
echo "MBQ PPL evaluation config"
echo "========================================="
echo "REPO_ROOT: $REPO_ROOT"
echo "GPU_ID: $GPU_ID"
echo "PYTHON_BIN: $PYTHON_BIN"
echo "MODEL_NAME: $MODEL_NAME"
echo "MODEL_PATH: $MODEL_PATH"
echo "W_BIT: $W_BIT"
echo "W_GROUP: $W_GROUP"
echo "A_BIT: $A_BIT"
echo "DATASET: $DATASET"
echo "DATA_PATH: $DATA_PATH"
echo "N_SAMPLES: $N_SAMPLES"
echo "SCALE_FILE_NAME: $SCALE_FILE_NAME"
echo "SCALE_PATH: $SCALE_PATH"
echo "RUN_IN_BACKGROUND: $RUN_IN_BACKGROUND"
echo "RESULT_JSON: $RESULT_JSON"
echo "LOG_FILE: $LOG_FILE"
echo "PYTHONPATH: $PYTHONPATH"
echo "HF_ENDPOINT: $HF_ENDPOINT"
echo "========================================="
echo "GPU status before launch:"
nvidia-smi --query-gpu=index,name,memory.free,memory.used,utilization.gpu --format=csv || true
echo "========================================="

if [ ! -f "$SCALE_PATH" ]; then
    echo "ERROR: MBQ scale file not found: $SCALE_PATH"
    echo "Set SCALE_PATH to an existing torch.save file generated by main_quant.py."
    exit 1
fi

run_eval() {
    trap '' HUP
    set +e
    CUDA_VISIBLE_DEVICES="${GPU_ID}" "$PYTHON_BIN" tests/test_PPL/eval_ppl.py \
        --model "$MODEL_NAME" \
        --model_args "pretrained=$MODEL_PATH" \
        --dataset "$DATASET" \
        --data_path "$DATA_PATH" \
        --n_samples "$N_SAMPLES" \
        --scale_path "$SCALE_PATH" \
        --w_bit "$W_BIT" \
        --w_group "$W_GROUP" \
        --a_bit "$A_BIT" \
        --double_quant \
        --double_quant_scale_bit "$DOUBLE_QUANT_SCALE_BIT" \
        --double_quant_scale_group "$DOUBLE_QUANT_SCALE_GROUP" \
        --pseudo_quant \
        --output_path "$RESULT_JSON" \
        --low_rank \
        --mixed_probe \
        --verbose
    exit_code=$?
    echo "========================================="
    if [ "${exit_code}" -eq 0 ]; then
        echo "Quantized PPL evaluation completed successfully!"
    else
        echo "Quantized PPL evaluation failed with exit code ${exit_code}!"
    fi
    echo "========================================="
    exit "${exit_code}"
}

# ========== 评估量化模型 ==========
if [ "$RUN_IN_BACKGROUND" = "1" ]; then
    run_eval &
    echo "========================================="
    echo "Background job started, PID: $!"
    echo "Log: ${LOG_FILE}"
    echo "========================================="
else
    echo "========================================="
    echo "Running in foreground"
    echo "Log: ${LOG_FILE}"
    echo "========================================="
    run_eval
fi
