# model args
model: internvl2
model_args: pretrained=OpenGVLab/InternVL2-8B

# calibration data args
calib_data: coco
n_samples: 128
data_path: "my-datasets/coco/data.json"
image_folder: "my-datasets"
few_shot_format: False # if True, concat two samples to simulate few shot
interleave_format: False # if True, insert pure text data between two image-text pairs to simulate interleave data
text_data_path: "" # You should specify this arg if you want to use interleave_format 

# quantization config
method: mbq
run_process: True
w_bit: 2
w_group: 64
distort: False # if True, use distort feature map during scale search process
reweight: True # if True, use avg gradient to reweight the loss of each modality
reweight_cache_path: "scale_cache/mbq/reweight/internvl2_8b_reweight.pt" # the path to cache the avg gradient for reweighting
loss_mode: mae
low_rank: True # if True, use low rank decomposition to optimize the scale search process
low_rank_rank: 256 # the rank for low rank decomposition
low_rank_attn_topk_ratio: 0.9
low_rank_mlp_topk_ratio: 0.9

# output args
scale_path: scale_cache/mbq/internvl2_8b_w2g64_svd_r_256.pt


